/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    // <summary>
    /// Get or Set a property of a Character component
    /// </summary>
    [CommandInfo("Property",
                 "Character",
                 "Get or Set a property of a Character component")]
    [AddComponentMenu("")]
    public class CharacterProperty : BaseVariableProperty
    {
        //generated property
        public enum Property
        {
            NameText,
            NameColor
        }


        [SerializeField]
        protected Property property;

        [SerializeField]
        protected CharacterData characterData;

        [SerializeField]
        [VariableProperty(typeof(StringVariable),
                          typeof(ColorVariable))]
        protected Variable inOutVar;

        public override void OnEnter()
        {
            var ios = inOutVar as StringVariable;
            var ioc = inOutVar as ColorVariable;


            var target = characterData.Value;

            switch (getOrSet)
            {
                case GetSet.Get:
                    switch (property)
                    {
                        case Property.NameColor:
                            ioc.Value = target.NameColor;
                            break;
                        case Property.NameText:
                            ios.Value = target.NameText;
                            break;
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                case GetSet.Set:
                    switch (property)
                    {
                        case Property.NameColor:
                            target.NameColor = ioc.Value;
                            break;
                        case Property.NameText:
                            target.NameText = ios.Value;
                            break;
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                default:
                    break;
            }

            Continue();
        }

        public override string GetSummary()
        {
            if (characterData.Value == null)
            {
                return "Error: no character set";
            }
            if (inOutVar == null)
            {
                return "Error: no variable set to push or pull data to or from";
            }

            return getOrSet.ToString() + " " + property.ToString();
        }

        public override Color GetButtonColor()
        {
            return new Color32(235, 191, 217, 255);
        }

        public override bool HasReference(Variable variable)
        {
            if (characterData.characterRef == variable || inOutVar == variable)
                return true;

            return false;
        }

    }
}